### ISSUE TITLE
Cannot read property 'get' of undefined 

### ISSUE THREAD

**Issue by liamjgm** [galvez/yamlful#1]
My modules include, '@nuxtjs/axios' and 'yamlful-nuxt

But I keep getting an error "client is undefined". I put a console log in the plugin.js like below and axios is undefined.

```
export default (ctx, inject) => {
  console.log(ctx.$axios) // <!----- console log here is undefined ---->
  const $api = api(ctx.$axios)
  extendStore(ctx, { $api })
  ctx.$api = $api
  inject('api', $api)
}
```

```
faqs:
  - method: all
    get: /faqs
  - method: allActive
    get: /faqs?active=1
  - method: get
    get: /faqs/:id
  - method: create
    post: /faqs
  - method: update
    put: /faqs/:id
  - method: remove
    delete: /faqs/:id
```

```
async asyncData({ app, error, $api }) {
    const response = await $api.faqs.all()
    console.log(response.data)
}
```
