### ISSUE TITLE
Simple assertions againts URL params

### ISSUE THREAD

**Issue by ValeriyDevPro** [galvez/yamlful#8]
Could we use assertions for routing? Similar to https://symfony.com/doc/4.1/routing.html#advanced-routing-example

Thanks
```yaml 
# config/routes.yaml
blog_list:
    path:      /blog/{page}
    controller: App\Controller\BlogController::list
    requirements:
        page: '\d+'
```
